name: Update update.json on main push

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Set version and package url
        id: set_vars
        run: |
          VERSION=${{ steps.get_tag.outputs.tag }}
          VERSION_NO_V=${VERSION#v}
          ZIP_URL="https://github.com/${{ github.repository }}/releases/download/${VERSION}/autoapudate.zip"
          echo "version=$VERSION_NO_V" >> $GITHUB_OUTPUT
          echo "package=$ZIP_URL" >> $GITHUB_OUTPUT

      - name: Generate update.json
        run: |
          cat <<EOF > update.json
{
  \"version\": \"${{ steps.set_vars.outputs.version }}\",
  \"package\": \"${{ steps.set_vars.outputs.package }}\",
  \"url\": \"https://github.com/${{ github.repository }}\"
}
EOF

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy update.json to gh-pages
        run: |
          cp update.json gh-pages/update.json

      - name: Commit and push update.json
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add update.json
          git commit -m "Update update.json [skip ci]" || echo "No changes to commit"
          git push
